-- vim.lsp.config("neocmake", {

-- single_file_support = true, -- suggested
-- init_options = {
--   format = {
--     enable = true, -- to use lsp format
--   },
--   lint = {
--     enable = true
--   },
--   semantic_token = false,
-- },
-- filetypes = { "cmake", "CMakeLists.txt", },
-- })
