#!/usr/bin/zsh

emulate -L zsh
local help verbose message file =(default)

test -z "$1" && exit 1

spaceleft=$(df -P "$1" | awk 'END{print $4}')
directory=${2:-.}

while IFS= read -r filename
do
    echo "$filename"

    filesize=$(du -k "$filename" | awk '{print $1}')

    if (( "$spaceleft" > "$filesize" )); then
        spaceleft=(($spaceleft - $filesize))
        echo moved
    fi
done < "$(ls -1 $directory)"
