#!/usr/bin/env zsh

# Clears the entire current line regardless of terminal size.
clear_this_line() {
    printf '\r'
    cols="$(tput cols)"
    for i in $(seq "$cols"); do
        printf ' '
    done
    printf '\r'
}

# Erases the amount of lines specified.
# $1 lines to erase
erase_lines() {
    # Default line count to 1.
    test -z "$1" && lines="1" || lines="$1"

    # This is what we use to move the cursor to previous lines.
    UP='\033[1A'

    # Erase.
    if [ "$lines" = 1 ]; then
        clear_this_line
    else
        lines=$((lines - 1))
        clear_this_line
        for i in $(seq "$lines"); do
            printf "$UP"
            clear_this_line
        done
    fi
}

# Reloads zsh config
if [ -n "$(jobs)" ]; then
    print -P "Error: %j job(s) in background"
else
    setopt no_notify
    notifybar "Reloaded zsh"
    erase_lines 2
    printf '\033[1A'
    kitten run-shell
fi
