[colors]
background = ${xrdb:background}
background-alt = #373B41
foreground = ${xrdb:foreground}
primary = ${xrdb:color7}
secondary = ${xrdb:color5}
alert = ${xrdb:color6}
disabled = ${xrdb:color2}

; dpi = 96
include-file = modules.ini
include-file = user_modules.ini
include-file = root.ini

[layout]
icon-font = 2
module-padding = 1
dim-value = 1

[settings]
pseudo-transparency = false

[global/wm]
margin-top = 5
margin-bottom = 5
